include: vega-lite
theme: jekyll-theme-cayman
title: Covid-19 visualização de casos no Brasil
description: Visualização de dados relacionadas a velocidade das ocorrências de mortes relacionadas ao Covid-19 por estado brasileiro
date: 2020-04-12 06:00
authors: Fernando Hannaka
comments: true
slug: altair-interactive
tags: covid, covid 19, coronavirus, mortes covid, covid hoje, estados brasileiros, brazil, duplicam
google_analytics: UA-163459825-1

